Controllers/BdHoraController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PIM_IV_Web.Models;

namespace PIM_IV_Web.Controllers
{
	public class BdHoraController : Controller
	{
		public IActionResult Index()
		{			
			return View();
		}
	}
}

Controllers/HoleritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PIM_IV_Web.Models;
using System.Drawing;

namespace PIM_IV_Web.Controllers
{
	public class HoleritesController : Controller
	{
		private readonly DesktopContext _dbContext;

		public HoleritesController(DesktopContext dbContext)
		{
			_dbContext=dbContext;
		}

		public Funcionario FuncionarioID(int ID)
		{
			return _dbContext.Funcionarios.FirstOrDefault(info => info.UsuarioId == ID);
		}

		public Holerite holeriteID(int ID)
		{
			return _dbContext.Holerites.FirstOrDefault(holerite => holerite.FuncionarioId == ID);
		}

		public IActionResult actionResult(int ID)
		{
			var info = FuncionarioID(ID);
			return View(info);
		}

		public IActionResult holeriteAction(int ID)
		{
			var holerite = holeriteID(ID);
			return View(holerite);
		}

		public IActionResult Index()
		{
			string SessionUser = HttpContext.Session.GetString("LoggedUserSession");

			if (string.IsNullOrEmpty(SessionUser)) return null;

			Usuario usuario = JsonConvert.DeserializeObject<Usuario>(SessionUser);

			var info = FuncionarioID(usuario.UsuarioId);

			actionResult(usuario.UsuarioId);
			holeriteAction(info.FuncionarioId);

			return View();
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home</title>
    <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PIM_IV_Web.styles.css" asp-append-version="true" />
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-thin-straight/css/uicons-thin-straight.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-straight/css/uicons-regular-straight.css'>
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <img src="./img/Icon monkey.png" />
            <a id="dashboard" asp-controller="Home" asp-action="Index">
                <i class="fi fi-ts-chart-line-up"></i>
                <span>Visão geral</span>
            </a>
            <a id="bancoHora" asp-controller="BdHora" asp-action="Index">
                <i class="fi fi-ts-clock-five"></i>
                <span>Banco de horas</span>
            </a>
            <a id="folhaPagamento" asp-controller="Holerites" asp-action="Index">
                <i class="fi fi-ts-hand-holding-usd"></i>
                <span>Folha de pagamento</span>
            </a>
            <a id="conf">
                <ion-icon name="settings-outline"></ion-icon>
                <span>Configurações</span>
            </a>
            <a class="leave" asp-controller="Login" asp-action="Leave" >
                <i class="fi fi-rs-exit"></i>
                <span>Sair</span>
            </a>
        </div>
        <main role="main">
            @RenderBody()
        </main>
        @await Component.InvokeAsync("Menu")
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://unpkg.com/phosphor-icons"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sing-In</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PIM_IV_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>